# -*- coding: utf-8 -*-
# 测试用配置文件
from datetime import timedelta

from flask_uploads import IMAGES, DOCUMENTS, TEXT, SCRIPTS, EXECUTABLES

# Flask 配置
ENV = 'development'
DEBUG = True
TESTING = True
PROPAGATE_EXCEPTIONS = True
PRESERVE_CONTEXT_ON_EXCEPTION = True
TRAP_HTTP_EXCEPTIONS = False
TRAP_BAD_REQUEST_ERRORS = True
SECRET_KEY = 'dev'
SESSION_COOKIE_NAME = 'session'
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
PERMANENT_SESSION_LIFETIME = timedelta(days=30)
SESSION_REFRESH_EACH_REQUEST = True
USE_X_SENDFILE = False
SEND_FILE_MAX_AGE_DEFAULT = timedelta(hours=12)
SERVER_NAME = 'application.test:5000'
APPLICATION_ROOT = '/'
PREFERRED_URL_SCHEME = 'http'
MAX_CONTENT_LENGTH = None
JSON_AS_ASCII = True
JSON_SORT_KEYS = True
JSONIFY_PRETTYPRINT_REGULAR = True
JSONIFY_MIMETYPE = 'application/json'
TEMPLATES_AUTO_RELOAD = True
EXPLAIN_TEMPLATE_LOADING = True
MAX_COOKIE_SIZE = 4093

# Flask-SQLAlchemy 配置
SQLALCHEMY_DATABASE_URI = 'postgresql://tricker:Tricker110112@localhost:5432/demo'
SQLALCHEMY_BINDS = None
SQLALCHEMY_ECHO = True
SQLALCHEMY_RECORD_QUERIES = True
SQLALCHEMY_NATIVE_UNICODE = True
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_POOL_TIMEOUT = 10 * 60
SQLALCHEMY_POOL_RECYCLE = 2 * 60 * 60
SQLALCHEMY_MAX_OVERFLOW = 10
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Flask-Restful 配置
BUNDLE_ERRORS = True

# Flask-Uploads 配置
UPLOADED_FILES_ALLOW = IMAGES + DOCUMENTS + TEXT + ('pdf',)
UPLOADED_FILES_DENY = SCRIPTS + EXECUTABLES

# 本地配置
API_URL = 'https://api.weixin.qq.com/cgi-bin/'
APP_ID = 'wx7f4bc57e093289b4'
APP_SECRET = '00e893edd2ea948c13f79cce996ad607'
