version: "3"

services:

  server:
    build: ./
    restart: always
    ports:
      - 80:5000
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: youyou
      POSTGRES_PASSWORD: WoAiLaoGong1314
